import type { Metadata } from 'next';
import '@comfanditd/chronux-ui/dist/style.css';
import './globals.css';
import { Auth } from '@/utils/guards/Auth';
import { StoreProvider } from '@/presentation/components/templates/provider';
import { SessionProviderWrapper } from '@/presentation';

export const metadata: Metadata = {
  title: 'Certificados - Comfandi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <StoreProvider>
            <Auth>{children}</Auth>
          </StoreProvider>          
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
