spring.application.name=korlon
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuracion healthcheck
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#Configuracion de Hibernate (manejo de entidades en JPA)
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracion del Scheduler (si deseas ajustar)
task.execution.pool.size=5
task.scheduling.pool.size=10

# Logging
logging.level.root=info
logging.level.co.com.confandi=debug

# AWS
aws.region: ${AWS_REGION}
aws.bucket-name: ${AWS_BUCKET_NAME}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}


# SMTP
spring.mail.host=${SMTP_MAIL_HOST}
spring.mail.port=587
spring.mail.username=${SMTP_MAIL_USERNAME}
spring.mail.password=${STMP_MAIL_PASSWORD}


# config template
app.file-path-template=${KORLON_TEMPLATE_PATH}
app.file-unavailable-path-template=${KORLON_UNAVAILABLE_PATH}
app.file-path-download=${KORLON_DOWNLOAD_PATH}

#security
api.basic_auth_user=${BASIC_AUTH_USER}
api.basic_auth_password=${BASIC_AUTH_PASSWORD}


api.phobos_baseurl=http://localhost:8080/api/v1/
api.phobos-user-name=admin
api.phobos-user-password=secret123

